### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by Loffes** [DemmyDemon/floatydraw#3]
![image](https://user-images.githubusercontent.com/43013032/109077053-dd80b280-76fb-11eb-9d84-770e8969b712.png)
With higher graphics settings, there's a black background, on lower it seems to be transparent.

**Comment by Loffes** [comment]
Appears to be MSAA, setting it to x4 or higher makes it appear. x2 and off makes it disappear

**Comment by DemmyDemon** [comment]
That's weird.
Good luck fixing it. I've effectively abandoned this project, as I'm no longer poking FiveM.
